spring.application.name=restyle-platform

# === Spring DataSource Configuration (PostgreSQL) ===
# spring.datasource.url=jdbc:postgresql://dpg-d3heqfbipnbc73d5mu00-a.oregon-postgres.render.com:5432/restyle
spring.datasource.url=jdbc:postgresql://localhost:5433/restyle-db
spring.datasource.username=postgres
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# === Spring JPA Configuration ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# === Hibernate Naming Strategy (si usabas snake_case) ===
spring.jpa.hibernate.naming.physical-strategy=com.metasoft.restyle.platform.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy

# === JWT Configuration ===
authorization.jwt.secret=YOUR_JWT_SECRET_KEY_HERE
authorization.jwt.expiration.days=7

# === OpenAI Configuration ===
openai.api.key=YOUR_OPENAI_API_KEY_HERE
openai.api.url=https://api.openai.com/v1/chat/completions

