spring.application.name=restyle-platform

# === Spring DataSource Configuration (PostgreSQL) ===
# spring.datasource.url=jdbc:postgresql://dpg-d3heqfbipnbc73d5mu00-a.oregon-postgres.render.com:5432/restyle
spring.datasource.url=jdbc:postgresql://localhost:5432/restyle-db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# === Spring JPA Configuration ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# === Hibernate Naming Strategy (si usabas snake_case) ===
spring.jpa.hibernate.naming.physical-strategy=com.metasoft.restyle.platform.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy

# === JWT Configuration ===
authorization.jwt.secret=8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
authorization.jwt.expiration.days=7

# === OpenAI Configuration ===
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions