spring.application.name=restyle-platform

# === Spring DataSource Configuration (PostgreSQL) ===
#spring.datasource.url=jdbc:postgresql://dpg-d3heqfbipnbc73d5mu00-a.oregon-postgres.render.com:5432/restyle
#spring.datasource.username=restyle_user
#spring.datasource.password=0UgcwYjEpRalJrUgzW01QYh0XC2T47AO
#spring.datasource.driver-class-name=org.postgresql.Driver

# === MYSQL VM DB ===
#spring.datasource.url=jdbc:mysql://192.168.100.38:3306/restyle?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=restyle
#spring.datasource.password=Mysql1234!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# === MySQL (Railway) ===
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:34167/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=QxSHJtjJsLehQApJTXUKfBIgxCTjjUug
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === Spring JPA Configuration ===
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# === Hibernate Naming Strategy ===
spring.jpa.hibernate.naming.physical-strategy=com.metasoft.restyle.platform.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy

# === JWT Configuration ===
authorization.jwt.secret=8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
authorization.jwt.expiration.days=7

# === OpenAI Configuration ===
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions
